# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  # Triggers the workflow on push or pull request events but only for the master branch
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
     types: [publish_blog,jss_workflow_trigger]
env:
  WEBAPP_NAME: SampleMVCProject.sln     # set this to your application's name
  WEBAPP_PACKAGE_PATH: 'published1'      # set this to the path to your web app project, defaults to the repository root
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    outputs:
      deployment-matrix: ${{ steps.deployment-matrix.outputs.matrix }}
    steps:
      - run : echo hello world
      - run : $a = ${{ github.event.client_payload.number}} 
      - run : Write-Host $a
      - name : Set deployment servers matrix
        id: deployment-matrix
  #          $a = ( Invoke-WebRequest "https://localhost:44356/api/github/mdts/job-news-email-stats-importer/runnersv2"  -UseBasicParsing).content
        run: |
          $a = (Invoke-WebRequest "http://164.55.120.194:85/deploymentjson/266c25a3-48cd-4bbc-ba61-37ca193259b2"  -UseBasicParsing).content
          Write-Host $a
          if($a -eq '{"message":"Error"}'){ Throw "Error in fetching deployment details"}
          if($a -eq '{"include":[]}'){ echo "::set-output name=isPresent::false"}
          else { echo "::set-output name=isPresent::true"}
          echo "::set-output name=matrix::$a"
  job2:
    needs: build
    strategy:
      matrix: ${{fromJSON(needs.build.outputs.deployment-matrix)}}
    runs-on: self-hosted
    steps:
      - run: echo "hello world"
    
      
    
      
