
on:    
    workflow_run:
        workflows: ["main"]
        types: [completed]
    workflow_dispatch:
    repository_dispatch:
        types:
          - webhook
jobs:
    on-success:
        runs-on: [deployment-test1]
        steps:
          - name: Download Artifacts
            uses: actions/download-artifact@v2
            with:
              name: "Build.zip"
          - name: Decompress download build zip
            run : Expand-Archive -Path ".\archive.zip" -DestinationPath "C:\" -Force
